#!/usr/bin/env pwsh
# 松鼠提醒 - 自动安装 Android SDK 并构建 APK

$ErrorActionPreference = "Stop"

Write-Host "🐿️ 松鼠提醒 APK 构建工具" -ForegroundColor Green
Write-Host "==========================" -ForegroundColor Green
Write-Host ""

# 设置路径
$SDK_DIR = "$env:USERPROFILE\Android\Sdk"
$CMDLINE_TOOLS = "$SDK_DIR\cmdline-tools\latest"
$GRADLE_WRAPPER = "$PSScriptRoot\android\gradlew"

# 检查 Java
Write-Host "📋 检查 Java..." -NoNewline
$java = Get-Command java -ErrorAction SilentlyContinue
if (-not $java) {
    Write-Host " 未安装" -ForegroundColor Red
    Write-Host ""
    Write-Host "❌ 需要安装 Java JDK 17" -ForegroundColor Red
    Write-Host "📥 下载地址: https://adoptium.net/" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "安装后请重新运行此脚本" -ForegroundColor Yellow
    exit 1
}

$javaVersion = java -version 2>&1 | Select-String "version" | Select-Object -First 1
Write-Host " $javaVersion" -ForegroundColor Green

# 检查 Android SDK
Write-Host "📋 检查 Android SDK..." -NoNewline
if (-not (Test-Path $SDK_DIR)) {
    Write-Host " 未安装，开始下载..." -ForegroundColor Yellow
    Write-Host ""
    
    # 创建目录
    New-Item -ItemType Directory -Force -Path "$SDK_DIR\cmdline-tools" | Out-Null
    
    # 下载 Android SDK
    $SDK_URL = "https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip"
    $SDK_ZIP = "$env:TEMP\android-sdk.zip"
    
    Write-Host "📥 下载 Android SDK (约 150MB)..." -ForegroundColor Cyan
    try {
        Invoke-WebRequest -Uri $SDK_URL -OutFile $SDK_ZIP -UseBasicParsing
    } catch {
        Write-Host "❌ 下载失败，请手动下载安装 Android Studio" -ForegroundColor Red
        Write-Host "📥 https://developer.android.com/studio" -ForegroundColor Cyan
        exit 1
    }
    
    # 解压
    Write-Host "📦 解压 SDK..." -ForegroundColor Cyan
    Expand-Archive -Path $SDK_ZIP -DestinationPath "$SDK_DIR\cmdline-tools" -Force
    Rename-Item "$SDK_DIR\cmdline-tools\cmdline-tools" "$SDK_DIR\cmdline-tools\latest" -ErrorAction SilentlyContinue
    
    # 设置环境变量
    Write-Host "⚙️ 配置环境变量..." -ForegroundColor Cyan
    [Environment]::SetEnvironmentVariable("ANDROID_SDK_ROOT", $SDK_DIR, "User")
    [Environment]::SetEnvironmentVariable("ANDROID_HOME", $SDK_DIR, "User")
    
    $env:ANDROID_SDK_ROOT = $SDK_DIR
    $env:ANDROID_HOME = $SDK_DIR
    $env:PATH = "$env:PATH;$SDK_DIR\cmdline-tools\latest\bin;$SDK_DIR\platform-tools"
    
    # 安装必要组件
    Write-Host "📦 安装 Android SDK 组件..." -ForegroundColor Cyan
    & "$CMDLINE_TOOLS\bin\sdkmanager.bat" "platforms;android-34" "build-tools;34.0.0" --sdk_root=$SDK_DIR
    
    Write-Host "✅ Android SDK 安装完成" -ForegroundColor Green
} else {
    Write-Host " 已安装" -ForegroundColor Green
    $env:ANDROID_SDK_ROOT = $SDK_DIR
    $env:ANDROID_HOME = $SDK_DIR
}

Write-Host ""
Write-Host "🔨 开始构建 APK..." -ForegroundColor Cyan
Write-Host ""

# 进入 Android 项目目录
$ANDROID_DIR = "$PSScriptRoot\android"
Set-Location $ANDROID_DIR

# 创建 local.properties
$LOCAL_PROPS = "local.properties"
"sdk.dir=$SDK_DIR" | Out-File -FilePath $LOCAL_PROPS -Encoding UTF8

# 下载 Gradle Wrapper
if (-not (Test-Path "$ANDROID_DIR\gradlew.bat")) {
    Write-Host "📥 下载 Gradle Wrapper..." -ForegroundColor Cyan
    
    # 创建基本的 Gradle wrapper
    @"
#!/usr/bin/env sh
##############################################################################
## Gradle start up script for POSIX generated by Gradle.
##############################################################################

# Attempt to set APP_HOME

# Resolve links: \$0 may be a link
app_path=\$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=\${app_path%"\${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "\$app_path" ]
do
    ls=\$( ls -ld "\$app_path" )
    link=\${ls#*' -> '}
    case \$link in             #(
      /*)   app_path=\$link ;; #(
      *)    app_path=\$APP_HOME\$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=\${0##*/}
APP_HOME=\$( cd "\${APP_HOME:-.}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "\$*"
} >&2

die () {
    echo
    echo "\$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "\$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=\$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "\$JAVA_HOME" ] ; then
    if [ -x "\$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=\$JAVA_HOME/jre/sh/java
    else
        JAVACMD=\$JAVA_HOME/bin/java
    fi
    if [ ! -x "\$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: \$JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "\$cygwin" && ! "\$darwin" && ! "\$nonstop" ; then
    case \$MAX_FD in #(
      max*)
        MAX_FD=\$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case \$MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "\$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to \$MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "\$cygwin" || "\$msys" ; then
    APP_HOME=\$( cygpath --path --mixed "\$APP_HOME" )
    CLASSPATH=\$( cygpath --path --mixed "\$CLASSPATH" )

    JAVACMD=\$( cygpath --unix "\$JAVACMD" )

fi

# Collect all arguments for the java command;
#   * \$@ is unset, use \$* instead of \$@ to handle empty arguments
set -- \
        "-Dorg.gradle.appname=\$APP_BASE_NAME" \
        -classpath "\$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "\$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n://services.gradle.org/distributions/gradle-8.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
"@ | Out-File -FilePath "$ANDROID_DIR\gradle\wrapper\gradle-wrapper.properties" -Encoding UTF8

    # 下载 gradle-wrapper.jar
    $WRAPPER_URL = "https://raw.githubusercontent.com/gradle/gradle/v8.2.0/gradle/wrapper/gradle-wrapper.jar"
    Invoke-WebRequest -Uri $WRAPPER_URL -OutFile "$ANDROID_DIR\gradle\wrapper\gradle-wrapper.jar" -UseBasicParsing
}

# 构建 APK
Write-Host "🔨 构建 Debug APK..." -ForegroundColor Cyan
Write-Host ""

& "$ANDROID_DIR\gradlew.bat" assembleDebug --no-daemon

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "🎉 APK 构建成功！" -ForegroundColor Green
    Write-Host ""
    Write-Host "📦 APK 位置:" -ForegroundColor Cyan
    Write-Host "   $ANDROID_DIR\app\build\outputs\apk\debug\app-debug.apk" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "📱 安装到手机:" -ForegroundColor Cyan
    Write-Host "   adb install app-debug.apk" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "🚀 或者手动复制 APK 到手机安装" -ForegroundColor Cyan
} else {
    Write-Host ""
    Write-Host "❌ 构建失败" -ForegroundColor Red
    Write-Host "请检查错误信息" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "按任意键退出..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
